### ISSUE TITLE
Unable to delete a custom App

### ISSUE THREAD

**Issue by hectorzin** [MiguelAngelLV/ha-awtrix#6]
**Miguel! What a great job — I love it!**

However, I ran into something while trying to make awesome use of this feature.

As the documentation states:
[Delete a Custom App](https://blueforcer.github.io/awtrix3/#/api?id=delete-a-custom-app)
_To remove a custom app, dispatch an empty payload/body to the associated topic or URL._

If you do this in HA:
```
action: mqtt.publish
data:
  topic: awtrix/custom/Energia
```

Then the custom app is deleted and no longer displayed on the screen.

So, I tried to replicate this using the custom component in the following way:
```
action: awtrix.custom_app
data:
  device: 46f7de6ece2c1000d30f840b31d60be8
  app: Energia

```
But instead of being removed, the result is a blank or black custom app, not its deletion.

Thanks!!!
